# Generated by Django 4.2.5 on 2023-10-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('DepartmentName', models.CharField(max_length=255)),
                ('vision', models.CharField(max_length=255)),
                ('mission', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Employe_Id_Number', models.PositiveIntegerField()),
                ('Gender', models.CharField(default=('Male', 'Female'), max_length=6)),
                ('Role', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='+254', max_length=15)),
                ('Email', models.EmailField(max_length=255)),
                ('EmergencyContact', models.CharField(max_length=255)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('BillingDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('MedicationID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicationName', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('UsageInstructions', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientID', models.CharField(default='RLONGHOS/01/', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='+254', max_length=15)),
                ('Email', models.EmailField(default='      @gmail.com', max_length=255)),
                ('InsuranceInfo', models.CharField(max_length=255)),
                ('EmergencyContact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SupplierName', models.CharField(max_length=255)),
                ('ContactPerson', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='+254', max_length=15)),
                ('Email', models.EmailField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('SupplyID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SupplyName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CurrentStock', models.IntegerField()),
                ('MinimumStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategories',
            fields=[
                ('TaxCategoryID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CategoryName', models.CharField(max_length=255)),
                ('TaxRate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('TestID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('TestName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ResultDate', models.DateField()),
                ('ResultDetails', models.TextField()),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctors')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patients')),
                ('TestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tests')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('OrderID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('OrderDate', models.DateField()),
                ('ExpectedDeliveryDate', models.DateField()),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderStatus', models.CharField(max_length=255)),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.purchaseorders')),
                ('SupplyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.supplies')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateField()),
                ('PaymentMethod', models.CharField(default=('M-Pesa', 'Bank', 'Insurance', 'Check', 'Cash'), max_length=255)),
                ('PaymentStatus', models.CharField(default=('Cleared', 'Pending', 'Invoiced'), max_length=255)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('NurseID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Specialization', models.CharField(max_length=255)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.employees')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('RecordID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AdmissionDate', models.DateField()),
                ('DischargeDate', models.DateField()),
                ('Diagnosis', models.TextField()),
                ('Treatment', models.TextField()),
                ('Prescriptions', models.TextField()),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctors')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patients')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTax',
            fields=[
                ('InvoiceTaxID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.invoices')),
                ('TaxCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.taxcategories')),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='PatientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patients'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('AttendanceID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AttendanceDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.employees')),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.employees'),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('AppointmentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AppointmentDateTime', models.DateTimeField()),
                ('Notes', models.TextField()),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctors')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patients')),
            ],
        ),
    ]
