# Generated by Django 4.2.5 on 2023-10-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_departments_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='DoctorID',
        ),
    ]
