# Generated by Django 4.2.5 on 2023-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_medicalrecords_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='AttendanceID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
